### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by shadykat01** [chrisjp/LetterboxdOnIMDb#1]
Appears to not work.

Tried on Firefox with Violentmonkey & Edge with Tampermonkey

![screenshot_3524](https://user-images.githubusercontent.com/109138507/201578040-92835ff8-cbe0-4846-b592-16204552f4a1.png)

**Comment by chrisjp** [comment]
Thanks for reporting this. I didn't realise that different *monkey addons/versions in different browsers have/had slightly different naming for the functions granted to the script, as Tampermonkey's documentation has not been updated with this information. Not only that, but Edge in particular was case-sensitive.

Just pushed a quick update (v1.0.1) which should fix this. I personally tested with Tampermonkey in Chrome/Brave/Edge and with Violentmonkey in Firefox.

Let me know if you're still have issues with it after updating.

**Comment by shadykat01** [comment]
> Thanks for reporting this. I didn't realise that different *monkey addons/versions in different browsers have/had slightly different naming for the functions granted to the script, as Tampermonkey's documentation has not been updated with this information. Not only that, but Edge in particular was case-sensitive.
> 
> Just pushed a quick update (v1.0.1) which should fix this. I personally tested with Tampermonkey in Chrome/Brave/Edge and with Violentmonkey in Firefox.
> 
> Let me know if you're still have issues with it after updating.

Thank you. Works great now. But there seems to be an issue when you use this script alongside this other one: https://greasyfork.org/en/scripts/15222-imdb-tomatoes

Then the RT rating appears twice.

![screenshot_3526](https://user-images.githubusercontent.com/109138507/201700617-043cad71-fd90-4496-b3b2-564a4f0c6418.png)

I'm not sure whether it's something that can be resolved by you or the other script author.

**Comment by shadykat01** [comment]
Script also appears to not work for upcoming movies on IMDb even though they have a rating on Letterboxd from people who saw it early at festivals.

Example: The Whale (2022)

https://www.imdb.com/title/tt13833688/

https://letterboxd.com/film/the-whale-2022/

I should mention the Rotten Tomatoes script https://greasyfork.org/en/scripts/15222-imdb-tomatoes doesn't work on unreleased movies either.

https://www.rottentomatoes.com/m/the_whale_2022

**Comment by chrisjp** [comment]
The duplication issue with that RT script should be fixed in v1.0.2, which I've just pushed.

As for the upcoming movies without an IMDb rating. My script checks for an existing IMDb rating and doesn't look up the Letterboxd rating unless one is found. I believe that RT script is working on a similar basis.

I can change this behaviour so it'll check regardless, but will probably need to do a lot more error handling for cases where there is no rating on either site, so it may take a little more time to ensure it's working correctly. I'll add it to the to-do list.

**Comment by chocolateboy** [comment]
Good to see another ratings widget :-)

The duplicate occurs because of the way you add your widget: by [replacing the inner HTML](https://github.com/chrisjp/LetterboxdOnIMDb/blob/79afca9f6dd0effe95149b795a7f98cfe0ccbabb/Letterboxd%20rating%20on%20IMDb.user.js#L149) of the ratings bar, rather than just prepending your widget. This breaks the event handlers for the IMDb ratings widget, so it's not possible to rate a title when using this userscript. It also breaks (i.e. removes) the RT rating widget's tooltip.

I would suggest just [prepending](https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend) your widget. You're doing it at `document-end`, so you don't have to worry about React reconciliation reverting the change.

**Comment by chrisjp** [comment]
@chocolateboy thanks for commenting. Yes it took me a bit to realise that was why it was happening, but I figured it out in the end, and I literally just pushed a fix for this a few minutes ago.

I actually ended up _appending_ it rather than prepending (using `appendChild()` in the absence of a `prependChild()` function). I saw your script does something similar, albeit with jQuery, and you force it left using CSS, which I too am doing now.

Good to know there is indeed a `prepend()` method too though, so thanks for linking that (it's probably obvious but I don't do much JS dev).

**Comment by shadykat01** [comment]
> The duplication issue with that RT script should be fixed in v1.0.2, which I've just pushed.
> 
> As for the upcoming movies without an IMDb rating. My script checks for an existing IMDb rating and doesn't look up the Letterboxd rating unless one is found. I believe that RT script is working on a similar idea.
> 
> I can change this behaviour so it'll check regardless, but will probably need to do a lot more error handling for cases where there is no rating on either site, so it may take a little more time to ensure it's working correctly. I'll add it to the to-do list.

@chocolateboy So the duplication appears to be fixed in this new version. Can you confirm the same? Also, would you be able to possibly share your thoughts on how or whether the widgets should be enabled on upcoming movies that doesn't yet have an IMDb rating?

**Comment by chrisjp** [comment]
Closing this as the original issue was already solved. Additionally, in the latest version efforts are made to include a Letterboxd link for upcoming movies.
